ALTER TABLE "SystemSettings"
ADD COLUMN "salesEmail" TEXT NOT NULL DEFAULT '',
ADD COLUMN "supportPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "replyToEmail" TEXT NOT NULL DEFAULT '',
ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "logoAssetId" TEXT,
ADD COLUMN "publicApiUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "defaultCurrency" TEXT NOT NULL DEFAULT 'EUR',
ADD COLUMN "sessionTtlHours" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN "passwordResetTtlMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "maxUploadMb" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "maxImageEdgePx" INTEGER NOT NULL DEFAULT 10000;
